"""Build a single-file Kaggle runner from the modular codebase.

The generated script (`kaggle_script.py`) embeds project modules and executes
`train.main()` directly in Kaggle without requiring the original folder tree.
"""

from pathlib import Path


ROOT = Path(__file__).parent
OUTPUT_FILE = ROOT / "kaggle_script.py"

# Core execution order (dependency-aware). Additional modules discovered under
# project packages are appended afterwards in deterministic order.
PRIORITY_MODULES = [
    "config",
    "core.device",
    "core.field_generation",
    "core.data_generator",
    "numerical_solvers.LAX",
    "numerical_solvers.LAX_torch",
    "core.initial_conditions",
    "core.losses",
    "core.model_architecture",
    "methods.adaptive_collocation",
    "methods.causal_training",
    "methods.temporal_splitting",
    "training.training_diagnostics",
    "training.physics",
    "training.trainer",
    "visualization.plot_utils",
    "visualization.plot_fields",
    "visualization.plot_comparisons",
    "visualization.plot_animations",
    "visualization.Plotting",
    "visualization.Interactive",
    "train",
]

# Only runtime-critical packages for train.py are bundled.
PACKAGE_DIRS = ["core", "methods", "numerical_solvers", "training", "visualization"]
DEPRECATED_SOLVER_SYMBOLS = (
    "lax_solution_torch",
    "lax_solution_3d_sinusoidal_torch",
)


def _module_name_from_path(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel.endswith("/__init__.py"):
        return rel[: -len("/__init__.py")].replace("/", ".")
    return rel[: -len(".py")].replace("/", ".")


def _iter_project_modules():
    for package_dir in PACKAGE_DIRS:
        package_path = ROOT / package_dir
        if not package_path.exists():
            continue
        for path in sorted(package_path.rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            yield path


def _ordered_module_specs():
    discovered = {}

    for root_file in ["config.py", "train.py"]:
        p = ROOT / root_file
        if p.exists():
            discovered[_module_name_from_path(p)] = p

    for path in _iter_project_modules():
        discovered[_module_name_from_path(path)] = path

    ordered = []
    used = set()

    for module_name in PRIORITY_MODULES:
        path = discovered.get(module_name)
        if path is not None:
            ordered.append((module_name, path))
            used.add(module_name)

    for module_name in sorted(discovered):
        if module_name in used:
            continue
        ordered.append((module_name, discovered[module_name]))

    return ordered


def _validate_no_deprecated_solver_usage(module_source_map: dict[str, str]) -> None:
    violations = {}
    for module_name, source in module_source_map.items():
        hits = [symbol for symbol in DEPRECATED_SOLVER_SYMBOLS if symbol in source]
        if hits:
            violations[module_name] = hits

    if violations:
        details = "; ".join(
            f"{module}: {', '.join(symbols)}"
            for module, symbols in sorted(violations.items())
        )
        raise RuntimeError(
            "Packaging aborted: deprecated solver symbol(s) found in bundled modules. "
            f"Replace with `lax_solver_torch` unified API first. Offenders -> {details}"
        )


def build_kaggle_script() -> str:
    module_specs = _ordered_module_specs()
    module_names = [name for name, _ in module_specs]
    module_source_map = {}

    module_source_entries = []
    for module_name, path in module_specs:
        source = path.read_text(encoding="utf-8")
        module_source_map[module_name] = source
        module_source_entries.append(f"    {module_name!r}: {source!r},")

    _validate_no_deprecated_solver_usage(module_source_map)

    lines = [
        "# Auto-generated by package_for_kaggle.py",
        "# Regenerate this file after any code changes.",
        "import sys",
        "import types",
        "",
        "MODULE_ORDER = [",
    ]
    lines.extend([f"    {name!r}," for name in module_names])
    lines.extend([
        "]",
        "",
        "MODULE_SOURCES = {",
    ])
    lines.extend(module_source_entries)
    lines.extend([
        "}",
        "",
        "def _ensure_parent_packages(module_name):",
        "    parts = module_name.split('.')",
        "    for i in range(1, len(parts)):",
        "        parent_name = '.'.join(parts[:i])",
        "        child_name = parts[i]",
        "        parent = sys.modules.get(parent_name)",
        "        if parent is None:",
        "            parent = types.ModuleType(parent_name)",
        "            parent.__package__ = parent_name",
        "            parent.__path__ = []",
        "            parent.__file__ = f'<packed:{parent_name}>'",
        "            sys.modules[parent_name] = parent",
        "            if i == 1:",
        "                globals()[parts[0]] = parent",
        "        next_parent_name = '.'.join(parts[:i+1])",
        "        child_mod = sys.modules.get(next_parent_name)",
        "        if child_mod is not None and not hasattr(parent, child_name):",
        "            setattr(parent, child_name, child_mod)",
        "",
        "def _create_module(module_name):",
        "    if module_name in sys.modules:",
        "        return sys.modules[module_name]",
        "    _ensure_parent_packages(module_name)",
        "    module = types.ModuleType(module_name)",
        "    module.__file__ = f'<packed:{module_name}>'",
        "    parent_name = module_name.rpartition('.')[0]",
        "    module.__package__ = parent_name if parent_name else module_name",
        "    if module_name in MODULE_SOURCES and module_name.count('.') == 0 and module_name not in ('config', 'train'):",
        "        module.__path__ = []",
        "    sys.modules[module_name] = module",
        "    if parent_name:",
        "        setattr(sys.modules[parent_name], module_name.split('.')[-1], module)",
        "    else:",
        "        globals()[module_name] = module",
        "    return module",
        "",
        "def _load_all_modules():",
        "    for module_name in MODULE_ORDER:",
        "        _create_module(module_name)",
        "    for module_name in MODULE_ORDER:",
        "        module = sys.modules[module_name]",
        "        source = MODULE_SOURCES[module_name]",
        "        code = compile(source, module.__file__, 'exec')",
        "        exec(code, module.__dict__)",
        "",
        "def main(argv=None):",
        "    _load_all_modules()",
        "    train_module = sys.modules['train']",
        "    if argv is None:",
        "        argv = sys.argv[1:]",
        "    train_module.main(argv)",
        "",
        "if __name__ == '__main__':",
        "    main()",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    script_text = build_kaggle_script()
    OUTPUT_FILE.write_text(script_text, encoding="utf-8")
    print(f"Created {OUTPUT_FILE.name} ({len(script_text.splitlines())} lines)")


if __name__ == "__main__":
    main()

